#!/usr/bin/env bash
# Build the Android app.
#
#   ./scripts/build-android.sh            # release .aab (Play Console upload)
#   ./scripts/build-android.sh apk        # release .apk (sideload/testing)
#   ./scripts/build-android.sh debug      # debug .apk
#
# Signing is driven by .env (see .env.sample): with ANDROID_KEYSTORE and the
# two passwords set, android/keystore.properties is regenerated here and the
# release build is signed. Without them Gradle still produces an unsigned
# artefact, which is fine locally but rejected by Play Console.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
TARGET="${1:-bundle}"

# --- toolchain -------------------------------------------------------------
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env)"
  fnm use 22 >/dev/null 2>&1 || true
fi

# AGP 8.13 / Gradle 8.13 need JDK 17 or 21 — and the system default here is
# JDK 8, which fails with an unhelpful class-version error. Pin explicitly.
if [ -z "${JAVA_HOME:-}" ] || ! "$JAVA_HOME/bin/java" -version 2>&1 | grep -qE '"(17|21)'; then
  for candidate in /usr/lib/jvm/java-21-openjdk /usr/lib/jvm/java-17-openjdk; do
    if [ -x "$candidate/bin/java" ]; then
      export JAVA_HOME="$candidate"
      break
    fi
  done
fi
echo "JAVA_HOME=${JAVA_HOME:-<system default>}"
"${JAVA_HOME:-/usr}/bin/java" -version 2>&1 | head -1

if [ -z "${ANDROID_HOME:-}" ] && [ -z "${ANDROID_SDK_ROOT:-}" ]; then
  echo "ANDROID_HOME / ANDROID_SDK_ROOT is not set." >&2
  exit 1
fi

if [ -f .env ]; then
  # shellcheck disable=SC1091
  set -a; . ./.env; set +a
fi

VERSION="$(node -p "require('./package.json').version")"
VERSION_CODE="$(node -p "require('./package.json').androidVersionCode")"
echo "Building Zitate-Bingo ${VERSION} (versionCode ${VERSION_CODE})"

# --- signing ---------------------------------------------------------------
# Generated from .env on every run, so the passwords live in exactly one
# place. The file is gitignored; Gradle reads it if it exists.
KEYSTORE_PROPS="$ROOT/android/keystore.properties"
if [ -n "${ANDROID_KEYSTORE:-}" ] && [ -n "${ANDROID_KEYSTORE_PASSWORD:-}" ]; then
  if [ ! -f "$ANDROID_KEYSTORE" ]; then
    echo "ANDROID_KEYSTORE points at a missing file: $ANDROID_KEYSTORE" >&2
    echo "Create it with the keytool command in .env.sample." >&2
    exit 1
  fi
  umask 077
  cat > "$KEYSTORE_PROPS" <<EOF
# Generated by scripts/build-android.sh from .env — do not edit or commit.
storeFile=${ANDROID_KEYSTORE}
storePassword=${ANDROID_KEYSTORE_PASSWORD}
keyAlias=${ANDROID_KEY_ALIAS:-upload}
keyPassword=${ANDROID_KEY_PASSWORD:-${ANDROID_KEYSTORE_PASSWORD}}
EOF
  echo "Signing with $(basename "$ANDROID_KEYSTORE") (alias ${ANDROID_KEY_ALIAS:-upload})"
else
  rm -f "$KEYSTORE_PROPS"
  echo "No ANDROID_KEYSTORE in .env — artefacts will be UNSIGNED."
fi

# --- web build -------------------------------------------------------------
echo
echo "==> Building web assets"
# The service worker is pointless inside the WebView (assets are already
# local) and swapping them mid-game is a risk, so the native build opts out.
VITE_NATIVE=1 yarn build

# .env may override the application id (see ANDROID_APP_ID).
yarn node scripts/sync-app-id.mjs

echo
echo "==> Syncing into the native project"
yarn cap sync android

# Launcher icons are derived from the SVG master, and `cap sync` does not
# touch them — regenerate so an icon change always reaches the APK.
yarn node scripts/gen-assets.mjs >/dev/null

# --- native build ----------------------------------------------------------
echo
case "$TARGET" in
  bundle) GRADLE_TASK="bundleRelease" ;;
  apk)    GRADLE_TASK="assembleRelease" ;;
  debug)  GRADLE_TASK="assembleDebug" ;;
  *)
    echo "Unknown target \"$TARGET\" — use bundle, apk or debug." >&2
    exit 1
    ;;
esac

echo "==> Gradle :app:${GRADLE_TASK}"
(cd android && ./gradlew --no-daemon "app:${GRADLE_TASK}")

# --- collect ---------------------------------------------------------------
# Only collect what THIS target just built. bundleRelease does not rebuild
# APKs, so an APK from an earlier version would otherwise be copied out and
# reported as if it were part of this build.
mkdir -p "$ROOT/build-output"
case "$TARGET" in
  bundle) find "$ROOT/build-output" -maxdepth 1 -name '*.apk' -delete ;;
  apk|debug) find "$ROOT/build-output" -maxdepth 1 -name '*.aab' -delete ;;
esac
shopt -s nullglob
for artefact in \
  android/app/build/outputs/bundle/release/*.aab \
  android/app/build/outputs/apk/release/*.apk \
  android/app/build/outputs/apk/debug/*.apk
do
  base="$(basename "$artefact")"
  case "$base" in
    *.aab) dest="$ROOT/build-output/quote-bingo-${VERSION}.aab" ;;
    *)     dest="$ROOT/build-output/${base}" ;;
  esac
  cp "$artefact" "$dest"
  echo "  → ${dest#"$ROOT"/}  ($(du -h "$dest" | cut -f1))"
done

# --- verify signing --------------------------------------------------------
# Play rejects an unsigned upload, and an unsigned build otherwise fails only
# at the end of a long manual upload.
if [ "$TARGET" != "debug" ]; then
  if [ -f "$KEYSTORE_PROPS" ]; then
    AAB="$ROOT/build-output/quote-bingo-${VERSION}.aab"
    if [ -f "$AAB" ]; then
      if unzip -l "$AAB" | grep -qiE 'META-INF/.*\.(RSA|DSA|EC)'; then
        echo "  signed: $(basename "$AAB")"
      else
        echo "  ERROR: $(basename "$AAB") is NOT signed." >&2
        exit 1
      fi
    fi

    APK="$ROOT/build-output/quote-bingo-release-${VERSION}.apk"
    if [ -f "$APK" ] && command -v apksigner >/dev/null 2>&1; then
      if apksigner verify "$APK" >/dev/null 2>&1; then
        echo "  signed: $(basename "$APK")"
      else
        echo "  ERROR: $(basename "$APK") is NOT signed." >&2
        exit 1
      fi
    fi
  else
    echo
    echo "  NOTE: no keystore configured — artefacts are UNSIGNED and Play"
    echo "        Console will reject them. See .env.sample."
  fi
fi

echo
echo "Done."
