#!/usr/bin/env node
/**
 * Renders every icon size the PWA, Play Store and Android launcher need from
 * the single SVG master in assets/icon/icon.svg.
 *
 *   yarn assets
 *
 * Requires ImageMagick 7 (`magick`) on PATH.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, copyFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const master = resolve(root, 'assets/icon/icon.svg');
const { LOCALES } = await import(resolve(root, 'scripts/locales.mjs'));

/** App background — matches the manifest theme colour and the SVG's own plate. */
const BG = '#1e1b4b';

function render(out, size, extra = []) {
  mkdirSync(dirname(out), { recursive: true });
  execFileSync('magick', [
    '-background', 'none',
    // Rasterise the SVG well above the target so downscaling stays crisp.
    '-density', '384',
    master,
    '-resize', `${size}x${size}`,
    ...extra,
    // Byte-for-byte reproducible output. Without these the PNG carries a
    // tIME chunk and ImageMagick's own date properties, so a rerun from an
    // unchanged master produces identical pixels under a new sha256 — which
    // would make every Play publish re-upload the icon in all nine languages
    // instead of skipping it.
    '-strip',
    '-define', 'png:exclude-chunk=time',
    out,
  ]);
  console.log(`  ${out.replace(`${root}/`, '')}  ${size}x${size}`);
}

console.log('PWA icons');
render(resolve(root, 'public/icon-192.png'), 192);
render(resolve(root, 'public/icon-512.png'), 512);

// Maskable: Android crops to a circle/squircle, so the artwork must sit inside
// the safe zone — render at 80% and pad back out on the plate colour.
console.log('Maskable icon');
render(resolve(root, 'public/icon-maskable.png'), 410, [
  '-background', BG,
  '-gravity', 'center',
  '-extent', '512x512',
]);

// Play Store listing icon: 512x512, no alpha channel (Play rejects alpha).
console.log('Play Store icon');
render(resolve(root, 'assets/play/icon-512.png'), 512, [
  '-background', BG,
  '-alpha', 'remove',
  '-alpha', 'off',
]);

// Android launcher densities, under Capacitor's res/mipmap-*.
const DENSITIES = [
  ['mdpi', 48],
  ['hdpi', 72],
  ['xhdpi', 96],
  ['xxhdpi', 144],
  ['xxxhdpi', 192],
];

const androidRes = resolve(root, 'android/app/src/main/res');
if (existsSync(androidRes)) {
  console.log('Android launcher icons');
  for (const [density, size] of DENSITIES) {
    render(resolve(androidRes, `mipmap-${density}/ic_launcher.png`), size);
    // The round variant is the same square art; Android masks it itself.
    render(resolve(androidRes, `mipmap-${density}/ic_launcher_round.png`), size);
    // Adaptive-icon foreground is a 108dp canvas whose outer 18dp on each side
    // can be cropped away, so the art may only occupy the middle 72dp (~66%).
    // The background comes from ic_launcher_background.xml, so this layer is
    // transparent outside the glyph.
    render(
      resolve(androidRes, `mipmap-${density}/ic_launcher_foreground.png`),
      Math.round(size * 0.66),
      ['-background', 'none', '-gravity', 'center', '-extent', `${size}x${size}`],
    );
  }

  // Adaptive-icon background layer: a flat plate behind the foreground.
  const bgXml = resolve(androidRes, 'values/ic_launcher_background.xml');
  mkdirSync(dirname(bgXml), { recursive: true });
  writeFileSync(
    bgXml,
    '<?xml version="1.0" encoding="utf-8"?>\n' +
      '<!-- Generated by scripts/gen-assets.mjs — do not edit. -->\n' +
      '<resources>\n' +
      `    <color name="ic_launcher_background">${BG.toUpperCase()}</color>\n` +
      '</resources>\n',
  );
  console.log(`  ${bgXml.replace(`${root}/`, '')}`);

  // Localised launcher labels, so the icon reads in the user's language.
  const { listings } = JSON.parse(
    readFileSync(resolve(root, 'store-listing/LISTINGS.json'), 'utf8'),
  );
  const escapeXml = (s) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/'/g, "\\'");

  console.log('Localised launcher labels');

  // values/ is the fallback for every language without its own folder, so it
  // must hold the ENGLISH title — capacitor.config.json's appName is German
  // and would otherwise show "Zitate-Bingo" to the entire non-listed world.
  // This file also carries Capacitor's package_name / custom_url_scheme, so
  // it is rewritten field-wise rather than regenerated.
  const defaultStrings = resolve(androidRes, 'values/strings.xml');
  if (existsSync(defaultStrings)) {
    const enTitle = escapeXml(listings.en.title);
    const updated = readFileSync(defaultStrings, 'utf8')
      .replace(/(<string name="app_name">)[^<]*(<\/string>)/, `$1${enTitle}$2`)
      .replace(/(<string name="title_activity_main">)[^<]*(<\/string>)/, `$1${enTitle}$2`);
    writeFileSync(defaultStrings, updated);
    console.log(`  values/strings.xml  ${listings.en.title}  (fallback)`);
  }

  // Every locale — including German — then gets its own values-<code>/.
  for (const locale of LOCALES) {
    if (locale.code === 'en') continue;
    const title = listings[locale.code]?.title;
    if (!title) continue;
    const dir = resolve(androidRes, `values-${locale.code}`);
    mkdirSync(dir, { recursive: true });
    const escaped = escapeXml(title);
    writeFileSync(
      resolve(dir, 'strings.xml'),
      '<?xml version="1.0" encoding="utf-8"?>\n' +
        '<!-- Generated by scripts/gen-assets.mjs — do not edit. -->\n' +
        '<resources>\n' +
        `    <string name="app_name">${escaped}</string>\n` +
        `    <string name="title_activity_main">${escaped}</string>\n` +
        '</resources>\n',
    );
    console.log(`  values-${locale.code}/strings.xml  ${title}`);
  }

  // Splash screens. Capacitor ships a WHITE stock splash, which flashes white
  // before the (dark) app paints and leaves the launch theme's light
  // status-bar icons invisible against it. Replace every density with a flat
  // plate carrying the icon, so launch matches the app in either theme.
  console.log('Splash screens');
  const SPLASHES = [
    ['drawable', 480, 320],
    ['drawable-port-mdpi', 320, 480],
    ['drawable-port-hdpi', 480, 800],
    ['drawable-port-xhdpi', 720, 1280],
    ['drawable-port-xxhdpi', 960, 1600],
    ['drawable-port-xxxhdpi', 1280, 1920],
    ['drawable-land-mdpi', 480, 320],
    ['drawable-land-hdpi', 800, 480],
    ['drawable-land-xhdpi', 1280, 720],
    ['drawable-land-xxhdpi', 1600, 960],
    ['drawable-land-xxxhdpi', 1920, 1280],
  ];
  for (const [dir, w, h] of SPLASHES) {
    const out = resolve(androidRes, dir, 'splash.png');
    mkdirSync(dirname(out), { recursive: true });
    // Icon at a quarter of the shorter edge, centred on the plate.
    const glyph = Math.round(Math.min(w, h) * 0.25);
    execFileSync('magick', [
      '-size', `${w}x${h}`,
      `xc:${BG}`,
      '(', '-background', 'none', '-density', '384', master, '-resize', `${glyph}x${glyph}`, ')',
      '-gravity', 'center',
      '-composite',
      '-strip',
      '-define', 'png:exclude-chunk=time',
      out,
    ]);
  }
  console.log(`  ${SPLASHES.length} splash images on ${BG}`);
}

// The favicon is the master itself.
copyFileSync(master, resolve(root, 'public/favicon.svg'));
console.log('\nDone.');
